version: '3'
services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    ports:
      - "9042:9042"
    networks:
      - cassandra-network

  cassandra-node2:
    image: cassandra:latest
    container_name: cassandra-node2
    environment:
      CASSANDRA_SEEDS: cassandra-node1
    ports:
      - "9043:9042"
    networks:
      - cassandra-network

networks:
  cassandra-network:
